[package]
name          = "qsv"
version       = "0.34.1"                                                  #:version
authors       = ["Joel Natividad <joel@datHere.com>"]
description   = "A high performance CSV command line toolkit."
documentation = "https://github.com/jqnatividad/qsv"
homepage      = "https://github.com/jqnatividad/qsv"
repository    = "https://github.com/jqnatividad/qsv"
readme        = "README.md"
keywords      = ["csv", "geocode", "data-engineering", "cli", "opendata"]
categories    = ["command-line-utilities", "parser-implementations"]
license       = "MIT OR Unlicense"
autotests     = false
edition       = "2021"
rust-version  = "1.59.0"
autobins      = false
include       = ["src/**/*", "LICENSE-MIT", "README.md", "CHANGELOG.md"]

[[bin]]
name    = "qsv"
test    = false
bench   = false
doctest = false
path    = "src/main.rs"

[[bin]]
name    = "qsvlite"
test    = false
bench   = false
doctest = false
path    = "src/mainlite.rs"

[[test]]
name = "tests"
path = "tests/tests.rs"

[profile.release]
codegen-units = 1
debug         = false
lto           = true
opt-level     = 3
strip         = true

[profile.test]
opt-level = 3

[dependencies]
anyhow = "1.0"
byteorder = "1.4"
cached = { version = "0.33", features = ["redis_store"] }
censor = { version = "0.2", optional = true }
chrono = { version = "0.4", optional = true }
crossbeam-channel = "0.5"
csv = "1.1"
csv-index = "0.1"
dateparser = "0.1"
docopt = "1"
eudex = { version = "0.1", optional = true }
filetime = "0.2"
flexi_logger = { version = "0.22", features = ["compress"] }
governor = "0.4"
grex = "1.3.0"
hlua = { version = "0.4", optional = true }
indicatif = "0.16"
itertools = "0.10"
jsonschema = { version = "0.15", features = [
    "resolve-file",
    "resolve-http",
], default-features = false }
jql = { version = "3.1", default-features = false }
log = "0.4"
mimalloc = { version = "0.1", default-features = false, optional = true }
once_cell = "1.10"
pyo3 = { version = "0.16", features = [
    "abi3-py38",
    "auto-initialize",
], optional = true }
qsv-stats = "0.3"
qsv_currency = { version = "0.5", optional = true }
rand = "0.8"
rayon = "1.5"
regex = "1"
reqwest = { version = "0.11", features = [
    "blocking",
    "cookies",
    "rustls-tls",
], default-features = false }
reverse_geocoder = { version = "3", optional = true }
self_update = { version = "0.28", features = [
    "archive-zip",
    "compression-zip-deflate",
    "rustls",
], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
strsim = { version = "0.10", optional = true }
sysinfo = "0.23"
tabwriter = "1.2"
test-data-generation = { version = "0.3", optional = true }
thiserror = "1.0"
thousands = "0.2"
threadpool = "1.8"
titlecase = { version = "1", optional = true }
uuid = { version = "0.8", features = ["v4"] }
vader_sentiment = { version = "0.1", optional = true }
whatlang = { version = "0.13", optional = true }

[dev-dependencies]
actix-governor   = "0.2"
actix-web        = "3.3"
assert-json-diff = "2.0"
quickcheck       = { version = "1", default-features = false }
redis            = "0.21"

[features]
default = ["mimalloc"]
apply = [
    "censor",
    "chrono",
    "eudex",
    "qsv_currency",
    "reverse_geocoder",
    "strsim",
    "titlecase",
    "vader_sentiment",
    "whatlang",
]
foreach = []
generate = ["test-data-generation"]
lua = ["hlua"]
python = ["pyo3"]
